// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCayJfGraK0Cz9P9IV6A9wLsFFWOPsksms',
    appId: '1:671965471547:web:ba2c20f7192535c0ae4d1e',
    messagingSenderId: '671965471547',
    projectId: 'exampratice12',
    authDomain: 'exampratice12.firebaseapp.com',
    storageBucket: 'exampratice12.firebasestorage.app',
    measurementId: 'G-3SSPZWNSGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4rfl4zmBOxgUKCfrNoUaiucuPlmVncpE',
    appId: '1:671965471547:android:15e493e6315561f2ae4d1e',
    messagingSenderId: '671965471547',
    projectId: 'exampratice12',
    storageBucket: 'exampratice12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWEexKcJp5lIgSPALRluvYHy_rMel0OQ',
    appId: '1:671965471547:ios:02f622cb02cdaf8fae4d1e',
    messagingSenderId: '671965471547',
    projectId: 'exampratice12',
    storageBucket: 'exampratice12.firebasestorage.app',
    iosBundleId: 'com.example.examPratice12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWEexKcJp5lIgSPALRluvYHy_rMel0OQ',
    appId: '1:671965471547:ios:02f622cb02cdaf8fae4d1e',
    messagingSenderId: '671965471547',
    projectId: 'exampratice12',
    storageBucket: 'exampratice12.firebasestorage.app',
    iosBundleId: 'com.example.examPratice12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCayJfGraK0Cz9P9IV6A9wLsFFWOPsksms',
    appId: '1:671965471547:web:8da23ef60860cb12ae4d1e',
    messagingSenderId: '671965471547',
    projectId: 'exampratice12',
    authDomain: 'exampratice12.firebaseapp.com',
    storageBucket: 'exampratice12.firebasestorage.app',
    measurementId: 'G-EG3VYSJL76',
  );
}
